AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Example slack api app

Globals:
  Function:
    Timeout: 3

Parameters:
  SigningSecret:
    Description: Slack App Signing Secret
    Type: String

Resources:
  SlackAppApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  SlackAppAPILambda:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: Prod
      Handler: slack_app.app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          SIGNING_SECRET: !Ref SigningSecret
      Events:
        GetIndex:
          Type: Api
          Properties:
            RestApiId: !Ref SlackAppApi
            Method: post
            Path: /

Outputs:
  SlackAppApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SlackAppApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SlackAppAPILambda:
    Description: "SlackAppAPILambda Function ARN"
    Value: !GetAtt SlackAppAPILambda.Arn
